---
- name: Install Docker on Linux servers
  hosts: servers
  become: yes
  tasks:
    - name: Install Docker on Amazon Linux / RHEL
      yum:
        name: docker
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install Docker on Ubuntu / Debian
      apt:
        name: docker.io
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Enable and start Docker service
      service:
        name: docker
        state: started
        enabled: yes
...
